name: Hello World

on:
  push :
    branches: 
      - master
    pull_request:
      - master
    workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello world"
          - echo "name is jugo kumar"
          - echo "Im Software Developer"
        shell: bash